import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Button from "react-bootstrap/Button";

// TODO: DEVAM

export default function Home() {
  return (
    <div className="bg-[#212529] text-gray-400 m-0 p-0 mt-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* about */}
      <div id="about">
        <h1 className="text-center p-2">Welcome to my Portfolio !</h1>
        <div className="flex flex-row gap-x-4 p-4 justify-center items-center">
          <div className="w-1/3">
            <span className="text-xl leading-10">Hello, i am Hikmet !</span> <br />
            <span className="text-xl">I am a</span>{" "}
            <span className="text-xl px-1 border-b-2 border-b-[#0dcaf0] hover:bg-[#0dcaf0] transition duration-300 text-gray-800">
              Frontend Web Developer
            </span>
            <p className="text-lg">
              from Turkey. I have a passion about designing and developing{" "}
              <span className="border-b-2 border-b-[#0dcaf0]">user interfaces</span>,{" "}
              <span className="border-b-2 border-b-[#0dcaf0]">web apps</span>,{" "}
              <span className="border-b-2 border-b-[#0dcaf0]">mobile apps</span> <br /> and more.
            </p>
          </div>
          <div className="rounded-full">
            <Image src={"/me.jpg"} alt="me" width={200} height={200} />
          </div>
        </div>
      </div>

      {/* languages and skills */}
      <div className="w-3/4 flex flex-col justify-center my-0 mx-auto">
        <h3 className="text-center">My Skills</h3>

        <div className="m-2">
          <h5>Languages</h5>
          <div className="flex flex-row gap-x-2 py-2">
            <Link href="#">
              <Button variant="outline-primary">HTML</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-warning">CSS</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-success">Javascript</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-danger">Typescript</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-light">Markdown</Button>
            </Link>
          </div>
        </div>

        <div className="m-2">
          <h5>Libraries and Frameworks</h5>
          <div className="flex flex-row gap-x-2 py-2">
            <Link href="#">
              <Button variant="outline-primary">Bootstrap</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-warning">Tailwind</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-success">MUI</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-success">Redux</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-success">Jest</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-success">Playwright</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-success">React Native</Button>
            </Link>
          </div>
        </div>

        <div className="m-2">
          <h5>Tools and more</h5>
          <div className="flex flex-row gap-x-2 py-2">
            <Link href="#">
              <Button variant="outline-primary">npm</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-warning">Webpack</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-success">JSON</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-danger">ESLint</Button>
            </Link>
            <Link href="#">
              <Button variant="outline-success">Prettier</Button>
            </Link>
          </div>
        </div>
      </div>

      <div id="projects">Projects</div>

      <div id="resume">Resume</div>
    </div>
  );
}
